app:
  ecr_uri: 313422618945.dkr.ecr.eu-central-1.amazonaws.com/devops-training-adonis/web-app
  image_tag: latest
  certificate_arn: arn:aws:acm:eu-central-1:313422618945:certificate/e78cff47-0633-4ea9-afbe-e1e3a26093b8
  name: devops-training-adonis
  hostname: web.adonis.apstellar.training
  ingressClassName: alb
  port:
    servicePort: 80
    containerPort: 3000
  requestCpu: 75m
  requestMem: 384Mi
  limitCpu: 90m
  limitMem: 500Mi
